export type FlightRecord = {
  date: string;
  airline: string;
  flight: string;
  from: string;
  to: string;
  canceled?: boolean;
  divertedTo?: string;
  aircraftType?: string;
  tailNumber?: string;
  gateDepartureScheduled?: string;
  gateArrivalScheduled?: string;
  takeoffScheduled?: string;
  landingScheduled?: string;
  gateDepartureActual?: string;
  gateArrivalActual?: string;
  takeoffActual?: string;
  landingActual?: string;
};

export type FlightStats = {
  flights: number;
  airlines: number;
  aircraftTypes: number;
  airports: number;
  airportCodes: string[];
  routes: number;
  totalHours: number;
  totalMinutes: number;
  averageFlightMinutes: number;
  durationBuckets: { short: number; medium: number; long: number };
  firstYear?: number;
  lastYear?: number;
  firstFlight?: { date: string; from: string; to: string; flight: string };
  lastFlight?: { date: string; from: string; to: string; flight: string };
  topAirlines: Array<{ name: string; flights: number }>;
  topAircraft?: string;
  topAircraftCount?: number;
  aircraftBreakdown: Array<{ name: string; flights: number; share: number }>;
  shortestFlight?: { flight: string; from: string; to: string; minutes: number };
  longestFlight?: { flight: string; from: string; to: string; minutes: number };
  topAirlineByTime?: { name: string; minutes: number };
  onTimeDepartures: number;
  delayedDepartures: number;
  onTimeArrivals: number;
  delayedArrivals: number;
  averageDelayMinutes: number;
  totalDelayMinutes: number;
  worstDelay?: { flight: string; from: string; to: string; minutes: number; phase: 'Departure' | 'Arrival' };
  delayByAirline: Array<{ name: string; averageDelay: number; flights: number }>;
  delayByOrigin: Array<{ code: string; averageDelay: number; flights: number }>;
  topOrigin?: { code: string; flights: number };
  topDestination?: { code: string; flights: number };
  topRoute?: { route: string; flights: number };
  topAirportOverall?: { code: string; visits: number };
  topYear?: number;
  topMonth?: string;
  topWeekday?: string;
  canceled: number;
  diverted: number;
};
